#!/usr/bin/env bash
# You need to have woff2 installed - See https://github.com/google/woff2

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 ICOMOON_BUNDLE.ZIP"
  exit 1
fi

cd -- "$(dirname $0)/.."

# Config
WORKDIR=/tmp/etsidemain-icomoon
STYLES_FILE=src/styles/_includes/icons_list.scss
FONTS_PATH=src/assets/fonts/icomoon
ICONS_JSON=utils/icons.json

rm -rf ${WORKDIR}
mkdir ${WORKDIR}


unzip "$1" -d ${WORKDIR}

cp ${WORKDIR}/fonts/* ${FONTS_PATH}
woff2_compress ${FONTS_PATH}/icomoon.ttf
echo -e "/* [!] DO NOT EDIT THIS FILE. Automatically generated from $0 */\n" > ${STYLES_FILE}
cat ${WORKDIR}/style.css | tail -n +27 >> ${STYLES_FILE}
cp ${WORKDIR}/selection.json ${ICONS_JSON}
